[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"


[project]
name = "mymllibrary"
version = "0.1.0"
description = "A beginner-friendly Python machine learning library implemented from scratch."
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}

authors = [
    {name = "Ayush Kumar Gour"}
]

dependencies = [
    "numpy",
    "matplotlib"
]


[tool.setuptools.packages.find]
include = ["myml*"]